alpha-blog/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

alpha-blog/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

alpha-blog/app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

alpha-blog/app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: {maximum: 25, minimum: 3}
  validates_uniqueness_of :name

  has_many :article_categories
  has_many :articles, through: :article_categories
end

alpha-blog/app/models/concerns/email_validator.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

alpha-blog/app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy

  before_save do
    self.email = email.downcase
  end

  validates :username, presence: true,
    uniqueness: { case_sensitive: false },
    length: { minimum: 3, maximum: 45 }
  validates :email, presence: true,
    uniqueness: { case_sensitive: false },
    length: { maximum: 105 },
    email: true

  has_secure_password
end

alpha-blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

alpha-blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully"
      # redirect_to article_path(@article)
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      # redirect_to article_path(@article)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end

end

alpha-blog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def index 
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was created successfully"
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name update successfully"
      redirect_to @category
    else
      render 'edit'
    end
  end

  private 

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only Admins could perform that action"
      redirect_to categories_path
    end  
  end

end

alpha-blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end
end

alpha-blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: session_params[:email].downcase)
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login detail"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end

end

alpha-blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successully sign up"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account informationwas succesfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articles_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end

end

alpha-blog/app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(image_src, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

end

alpha-blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

alpha-blog/app/helpers/pages_helper.rb
module PagesHelper
end

alpha-blog/app/views/articles/_article.html.erb
<div class="row justify-content-md-center">
  <div class="col-8 mt-4">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header font-italic">
        by <%= link_to article.user.username, user_path(article.user) %>
        <% if article.categories.any? %>
        <div class="mt-2">
          <%= render partial: 'categories/badge', collection: article.categories, as: 'category' %> 
        </div>
        <% end %>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
        <p class="card-text"><%= truncate(article.description, length: 100) %></p>
        <%= link_to "View", article_path(article), class: "btn btn-outline-primary" %>
        <% if logged_in? && (article.user == current_user || current_user.admin?) %>
          <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-success" %>
          <%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-warning" %>
        <% end %>
      </div>
      <div class="card-footer text-muted">
        <small>Created <%= time_ago_in_words(article.created_at) %>,
          edited <%= time_ago_in_words(article.updated_at) %> ago</small>
      </div>
    </div>
  </div>
</div>

alpha-blog/app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with model: @article, local: true, class: "shadow p-3 mb-3 bg-info rounded" do |f| %>
      <div class="form-group row">
        <%= f.label :title, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :description, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :category, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.collection_select(:category_ids, Category.all, :id, :name,
            { prompt: "Please select Category" },
            { multiple: true,
              size: 3, 
              class: "custom-select shadow rounded" }) %>
        </div>
      </div>
      <div class="form-group row justify-content-center">
        <%= f.submit class: "btn btn-outline-light btn-large" %>
      </div>
      <% end %>
    </div>
    <div class="mb-3">
      <p>
        <%= link_to "[ Cancel and return to articles listing ]", articles_path, class: "text-info" %>
      </p>
    </div>
  </div>
</div>

alpha-blog/app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>
<%= render 'form' %>

alpha-blog/app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>

<div class="container">
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

  <% @articles.each do |article| %>
    <%= render 'article', article: article %>
  <% end %>

  <div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>

  <p class="text-center mb-4">
    <%= link_to 'Create new article', new_article_path %>
  </p>

</div>

alpha-blog/app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>
<%= render 'form' %>

alpha-blog/app/views/articles/show.html.erb
<div class="container">
  <h1 class="text-center mt-4">Show article details</h1>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= link_to @article.user.username, user_path(@article.user) %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
          <% if @article.categories.any? %>
            <div class="mt-2">
              <%= render partial: 'categories/badge', collection: @article.categories, as: 'category' %> 
            </div>
          <% end %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to @article.title, article_path(@article), class: "text-success" %></h5>
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-success" %>
            <%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-warning" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %>,
            edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
  <p class="text-center mb-4">
    <%= link_to "[ Return to articles listing ]", articles_path, class: "text-info" %>
  </p>
</div>

alpha-blog/app/views/categories/_badge.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-primary mr-1" %>

alpha-blog/app/views/categories/_category.html.erb
<div class="row justify-content-md-center">
  <div class="col-4 mt-4">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-body">
        <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
        <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>  
      </div>
      <div class="card-footer text-muted">
        <small>Created <%= time_ago_in_words(category.created_at) %>,
          edited <%= time_ago_in_words(category.updated_at) %> ago</small>
      </div>
    </div>
  </div>
</div>

alpha-blog/app/views/categories/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @category %>
      <%= form_with model: @category, local: true, class: "shadow p-3 mb-3 bg-info rounded" do |f| %>
      <div class="form-group row">
        <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a category name" %>
        </div>
      </div>
      <div class="form-group row justify-content-center">
        <%= f.submit class: "btn btn-outline-light btn-large" %>
      </div>
      <% end %>
    </div>
    <div class="mb-3">
      <p>
        <%= link_to "[ Cancel and return to category listing ]", categories_path, class: "text-info" %>
      </p>
    </div>
  </div>
</div>

alpha-blog/app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category</h1>
<%= render 'form' %>

alpha-blog/app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="container">
  <div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
  </div>

  <% @categories.each do |category| %>
    <%= render 'category', category: category %>
  <% end %>

  <div class="flickr_pagination mb-4">
    <%= will_paginate @categories, :container => false %>
  </div>

  <p class="text-center mb-4">
    <%= link_to 'Create new category', new_category_path %>
  </p>

</div>

alpha-blog/app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create new category</h1>
<%= render 'form' %>

alpha-blog/app/views/categories/show.html.erb
<h1 class="text-center mt-4"><%= @category.name %></h1>

<div class="text-center mt-4">
  <% if logged_in? && current_user.admin? %>
    <%= link_to "Edit", edit_category_path(@category), class: "btn btn-outline-success" %>
  <% end %>
</div>

<h3 class="text-center mt-4">Articles</h3>
<div class="container">
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

  <% @articles.each do |article| %>
    <%= render 'articles/article', article: article %>
  <% end %>

  <div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>
</div>

alpha-blog/app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-light text-dark">
  <div class="containter text-center">
    <small>Copyright &copy; <%= link_to "Saltsoft", "https://saltsoft.pl", class: "text-dark" %></small>
  </div>
</footer>

alpha-blog/app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
  <% if name == "alert" %>
    <div class="alert alert-danger alert-dismissible fade show"" role=" alert">
  <% elsif name == "notice" %>
    <div class="alert alert-success alert-dismissible fade show"" role=" alert">
  <% else %>
    <div class="alert alert-warning alert-dismissible fade show"" role=" alert">
  <% end %>
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <% end %>
</div>

alpha-blog/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light text-dark">
  <%= link_to "AlphaBlog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Articles", articles_path, class: "dropdown-item" %>
          <% if logged_in? %>  
            <%= link_to "New article", new_article_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li> 
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Categories", categories_path, class: "dropdown-item" %>
          <% if logged_in? && current_user.admin? %>  
            <%= link_to "New category", new_category_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li> 
      <% if !logged_in? %>
        <li class="nav-item">
          <%= link_to "Log in", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", signup_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item", method: :delete, data: {confirm: "Are you sure?"} %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", logout_path, class: "nav-link", method: :delete %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

alpha-blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>AlphaBlog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="d-flex flex-column">
  <%= render 'layouts/navigation' %>
  <div id="page-content">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>

</html>

alpha-blog/app/views/pages/about.html.erb
<h1>About</h1>


<%= link_to "Home", root_path %>

alpha-blog/app/views/pages/home.html.erb
<div class="constainer" id="home-container">
  <div class="jumbotron text-center">
    <h1 class="display-4">AlphaBlog!</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <p class="lead">
      <%= link_to "Sign up!", signup_path, class: "btn btn-primary btn-success btn-lg" %>
    </p>
  </div>
</div>