message_me/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'chatroom#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'login', to: 'sessions#destroy'

  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

message_me/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  validates :body,
    presence: true
  
  scope :last20, -> { order(:created_at).last(20) }
end

message_me/app/models/user.rb
class User < ApplicationRecord
  has_many :messages

  validates :username, 
    presence: true,
    uniqueness: { case_sensitive: false },
    length: { minimum: 3, maximum: 45 }

  has_secure_password
end

message_me/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash.alert = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

message_me/app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController

  # GET /chatroom
  def index
    @message = Message.new
    @messages = Message.last20
  end

end

message_me/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  # POST /message
  def create
    @message = current_user.messages.build(message_params)
    if !@message.save
      flash.alert = "Message couldn't be added ..."
    end
    ActionCable.server.broadcast "chatroom_channel", mod_message: message_render(@message)
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end

end

message_me/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, except: [:destroy]

  # GET /login
  def new
  end

  # POST /login
  def create
    user = User.find_by(username: session_params[:username])
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      flash.notice = "Logged in successfully"
      redirect_to root_path
    else
      flash.now.alert = "There was something wrong with your login detail"
      render 'new'
    end
  end

  # DELETE /login
  def destroy
    if session[:user_id]
      flash.notice = "Logged out"
    end
    session[:user_id] = nil
    redirect_to login_path
  end

  private

  def session_params
    params.require(:session).permit(:username, :password)
  end

  def logged_in_redirect
    if logged_in?
      flash.alert = "You are already logged in"
      redirect_to root_path
    end
  end
end

message_me/app/helpers/chatroom_helper.rb
module ChatroomHelper
end

message_me/app/helpers/messages_helper.rb
module MessagesHelper
end

message_me/app/helpers/sessions_helper.rb
module SessionsHelper
end

message_me/app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="red circular coffee icon"></i>
  Say something
</h4>

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: { class: "ui reply form", role: "form"}, url: message_path, remote: true) do |message_form| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= message_form.text_field :body, placeholder: "Share something" %> 
              <%= message_form.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
    </div>
    </div>
  </div>
  <div class="four wide column">
    <div class="ui fluid raised card chatbox"> 
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="item">
            Luke
          </a>
          <a class="item">
            All
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

message_me/app/views/layouts/_messages.html.erb
<div class="container">
  <% if flash.notice %>
    <div class="ui success message" role="alert">
      <div class="header">
        Great!!!
      </div>
      <i class="close icon"></i>
      <%= flash.notice %>
    </div>
  <% end %>
  <% if flash.alert %>
    <div class="ui negative message" role="alert">
      <div class="header">
        Something went wrong ...
      </div>
      <i class="close icon"></i>
      <%= flash.alert %>
    </div>
  <% end %>
</div>

message_me/app/views/layouts/_navigation.html.erb
<div class="ui small inverted menu">
  <div class="ui container">
    <%= link_to "Chatroom", root_path, class: "item" %>
    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
            <%= link_to "Log out", login_path, class: "item", method: :delete %>
          <% else %>
            <%= link_to "Log in", login_path, class: "item" %>
          <% end %>
        </div>
      </div>
      <% if !logged_in? %>  
        <div class="item">
          <%= link_to "Log in", login_path, class: "ui primary button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

message_me/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/navigation' %>
      <div class="ui container">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
  </body>
</html>

message_me/app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%= message.body %>
    </div>
  </div>
</div>