stock_tracker/config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: %i[create destroy]
  devise_for :users

  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'

  get 'my_friends', to: 'users#my_friends'
  get 'search_friends', to: 'users#search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

stock_tracker/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

stock_tracker/app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

stock_tracker/app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name,
        last_price: client.price(ticker_symbol))
  rescue StandardError => e
    nil
  end

  def self.client
    IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_api[:publishable_token],
      secret_token: Rails.application.credentials.iex_api[:secret_token],
      endpoint: Rails.application.credentials.iex_api[:base_url]
    )
  end
end

stock_tracker/app/models/user.rb
class User < ApplicationRecord
  MAX_OF_STOCKS = 3

  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  validates_length_of :stocks, maximum: MAX_OF_STOCKS

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def can_track_stock?(ticker_symbol)
    stocks.count < MAX_OF_STOCKS && !stocks.find_by(ticker: ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name

    'Anonymous'
  end
end

stock_tracker/app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

stock_tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  # https://github.com/heartcombo/devise/wiki/How-To:-Create-custom-layouts
  def layout_by_resource
    if devise_controller?
      'devise'
    else
      'application'
    end
  end
end

stock_tracker/app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_with_stock_as_json
      else
        flash_alert_and_back_to_my_portfolio 'Please provide a valid symbol to search'
      end
    else
      flash_alert_and_back_to_my_portfolio 'Please provide a symbol to search'
    end
  end

  private

  def respond_with_stock_as_json
    respond_to do |format|
      format.js { render partial: 'users/result' }
    end
  end

  def flash_alert_and_back_to_my_portfolio(alert_message)
    flash.now[:alert] = alert_message
    respond_to do |format|
      format.js { render partial: 'users/result' }
    end
  end
end

stock_tracker/app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.find_by(ticker: params[:ticker]) || Stock.new_lookup(params[:ticker])
    stock.save
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was added to your portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    UserStock.find_by(user: current_user, stock_id: params[:id]).delete
    flash[:notice] = 'Stock was removed from your portfolio'
    redirect_to my_portfolio_path
  end
end

stock_tracker/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

  def search
    if params[:friend].present?
      @friend = params[:friend]
      if @friend
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        flash.now[:alert] = 'Please provide a friend to search'
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      end
    else
      flash_alert_and_back_to_my_portfolio 'Please provide a symbol to search'
      flash.now[:alert] = 'Please provide a friend to search'
      respond_to do |format|
        format.js { render partial: 'users/friend_result' }
      end
    end
  end
end

stock_tracker/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

stock_tracker/app/helpers/application_helper.rb
module ApplicationHelper
end

stock_tracker/app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

stock_tracker/app/helpers/users_helper.rb
module UsersHelper
end

stock_tracker/app/helpers/welcome_helper.rb
module WelcomeHelper
end

stock_tracker/app/views/friends/_list.html.erb
<div class="row">
  <div class="col-sm-9">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Email</th>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <th scope="row"><%= friend.email %></th>
            <td><%= friend.first_name %></td>
            <td><%= friend.last_name %></td>
            <td>
              <!-- prettier-ignore -->
              <%= link_to 'Stop following', '#', method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-warning' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

stock_tracker/app/views/layouts/_messages.html.erb
<!-- prettier-ignore -->
<% if notice %>
<div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<!-- prettier-ignore -->
<% end %> 
<% if alert %>
<div class="alert alert-danger alert-dismissible fade show m-1" role="alert">
  <%= alert %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<!-- prettier-ignore -->
<% end %>

stock_tracker/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <!-- prettier-ignore -->
    <%= link_to 'Stock Tracker', root_path, class: 'navbar-brand' %>
    <% if user_signed_in? %>
      <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <!-- prettier-ignore -->
          <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
            <!-- prettier-ignore -->
            <%= link_to 'My Portfolio', my_portfolio_path, class: 'nav-link' %>
          </li>
          <li class="nav-item <%= 'active' if request.path == my_friends_path %>">
            <!-- prettier-ignore -->
            <%= link_to 'My Friends', my_friends_path, class: 'nav-link' %>
          </li>
          <li class="nav-item dropdown">
            <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
            >
              Profile
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to edit_user_registration_path, class: 'dropdown-item' do%>
                <%= fa_icon 'edit' %> Edit Profile 
              <% end %>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item user-name">
            <%= fa_icon 'user' %> <%= current_user.full_name %>
          </li>
          <li class="nav-item pl-2 pr-2">
            <!-- prettier-ignore -->
            <%= link_to(fa_icon("sign-out"), destroy_user_session_path, class: 'btn btn-xs btn-danger', method: :delete) %>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input
          class="form-control mr-sm-2"
          type="search"
          placeholder="Search"
          aria-label="Search"
        />
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
              Search
            </button>
          </form>
        <% end %>
      </div>
    </div>
  </nav>

stock_tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockTracker</title>

    <!-- prettier-ignore -->
    <%= csrf_meta_tags %> 
    <%= csp_meta_tag %> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <!-- prettier-ignore -->
      <%= render 'layouts/messages' %>
      <%= render 'layouts/navigation' %>
      <%= yield %>
    </div>
  </body>
</html>

stock_tracker/app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockTracker</title>

    <!-- prettier-ignore -->
    <%= csrf_meta_tags %> 
    <%= csp_meta_tag %> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <!-- prettier-ignore -->
      <%= render 'layouts/messages' %>
      <%= render 'layouts/navigation' %>
      <div class="row">
        <div class="col-3"></div>
        <div class="col">
          <div class="devise">
            <!-- prettier-ignore -->
            <%= yield %>
          </div>
        </div>
        <div class="col-3"></div>
      </div>
    </div>
  </body>
</html>

stock_tracker/app/views/stocks/_list.html.erb
<div class="row">
  <div class="col-sm-9">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @tracked_stocks.each do |stock| %>
        <tr>
          <th scope="row"><%= stock.ticker %></th>
          <td><%= stock.name %></td>
          <td><%= stock.last_price %></td>
          <td>
            <!-- prettier-ignore -->
            <%= link_to 'Remove', user_stock_path(stock), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-warning' %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>